name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build Backend
      run: |
        cd revHubBack
        ./mvnw clean package -DskipTests
        
    - name: Build Frontend
      run: |
        cd RevHub
        npm ci
        npm run build
        
    - name: Build Docker Images
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/revhub-backend:latest ./revHubBack
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/revhub-frontend:latest ./RevHub
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/revhub-backend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/revhub-frontend:latest
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/revhub
          git pull origin main
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d